### ISSUE TITLE
i2c using 12bit values instead of 14bit

### ISSUE THREAD

**Issue by tomwaters** [16n-faderbank/16next_firmware#11]
The original 16n would send fader values over i2c in the range [0 - 16383](https://github.com/16n-faderbank/16n/blob/main/firmware/16n_faderbank_firmware/16n_faderbank_firmware.ino#L359) whereas the 16nx sends the 12bit value from the ADC (0 - 4095). 

You could probably just val * 4 the current value to get close enough although val * 16383 / 4095 probably wont cause any performance issues.

**Comment by infovore** [comment]
Good catch. I think for speed we could `<< 2` it rather than `*4`. You won't get any more accuracy, but scripts wouldn't break.

**Comment by infovore** [comment]
Thanks for this - fixed as of [v3.0.3](https://github.com/16n-faderbank/16next_firmware/releases/tag/v3.0.3).
